// Copyright 2016-2020 ?????????????. All Rights Reserved.
#include <Reflection\Private\ReflectionAllocators.h>
#include <Allocators\RootAllocator.h>

namespace Engine
{
	namespace Reflection
	{
		namespace Private
		{
			CREATOR_DEFINITION(ReflectionAllocators);

			DynamicSizeAllocator* ReflectionAllocators::AutoGeneratedAllocator = nullptr;

			ReflectionAllocators::ReflectionAllocators(void)
			{
				static DynamicSizeAllocator autoGeneratedAllocator("AutoGenerated Reflection Allocator", RootAllocator::GetInstance());
				AutoGeneratedAllocator = &autoGeneratedAllocator;
			}
		}
	}
}